# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/GPTutorial',
                'doc_host': 'https://BorjaRequena.github.io',
                'git_url': 'https://github.com/BorjaRequena/GPTutorial',
                'lib_path': 'GPTutorial'},
  'syms': {}}
